# Generated by Django 5.2 on 2025-05-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_months_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="budget",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="base.budget"
            ),
        ),
    ]
