# Generated by Django 5.2 on 2025-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20250518_1615"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
