# Generated by Django 5.2 on 2025-05-17 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_expenses_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("pets", "Pets"),
                            ("bills", "Bills"),
                            ("trav", "Travel"),
                            ("app", "Apartment"),
                            ("shop", "Shoppinm"),
                            ("gym", "Gym"),
                            ("date", "Date"),
                            ("extra", "Extra"),
                            ("save", "Saving"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="expenses",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.categories",
            ),
        ),
    ]
