# Generated by Django 5.2 on 2025-05-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_categories_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenses",
            name="adjust_type",
            field=models.CharField(
                choices=[("add", "Add"), ("deduct", "Deduct")], null=True
            ),
        ),
    ]
