# Generated by Django 5.2 on 2025-05-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_categories_alter_expenses_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(
                choices=[
                    ("pets", "Pets"),
                    ("bills", "Bills"),
                    ("trav", "Travel"),
                    ("app", "Apartment"),
                    ("shop", "Shopping"),
                    ("gym", "Gym"),
                    ("date", "Date"),
                    ("extra", "Extra"),
                    ("save", "Saving"),
                ],
                max_length=20,
            ),
        ),
    ]
