# Generated by Django 5.2 on 2025-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_expenses_adjust_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="expense",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
