# Generated by Django 5.2 on 2025-05-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_expenses_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
