# Generated by Django 5.2 on 2025-05-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_categories_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="category",
            field=models.CharField(
                choices=[
                    ("pets", "Pets"),
                    ("bills", "Bills"),
                    ("trav", "Travel"),
                    ("app", "Apartment"),
                    ("shop", "Shopping"),
                    ("gym", "Gym"),
                    ("date", "Date"),
                    ("extra", "Extra"),
                    ("save", "Saving"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
